name: Build and Release JARs

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      release_type:
        description: 'Set to "main" for full release; else pre-release'
        required: false
        default: ''

permissions:
  contents: write   # needed to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      jars: ${{ steps.set-jars.outputs.jars }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Compile and package CRAlgorithmCheck
        run: |
          mkdir -p out/CRAlgorithmCheck
          javac CRAlgorithmCheck/CRAlgorithmCheck.java -d out/CRAlgorithmCheck
          jar cfe CRAlgorithmCheck.jar CRAlgorithmCheck -C out/CRAlgorithmCheck .

      - name: Compile and package CRCountTo1Million
        run: |
          mkdir -p out/CRCountTo1Million
          javac CRCountTo1Million/CRCountTo1Million.java -d out/CRCountTo1Million
          jar cfe CRCountTo1Million.jar CRCountTo1Million -C out/CRCountTo1Million .

      - name: Compile and package CRForceCRC32
        run: |
          mkdir -p out/CRForceCRC32
          shopt -s globstar
          javac CRForceCRC32/**/*.java -d out/CRForceCRC32
          jar cfe CRForceCRC32.jar CRForceCRC32 -C out/CRForceCRC32 .

      - name: Compile and package CRIntCheck
        run: |
          mkdir -p out/CRIntCheck
          javac CRIntCheck/CRIntCheck.java -d out/CRIntCheck
          jar cfe CRIntCheck.jar CRIntCheck -C out/CRIntCheck .

      - name: Compile and package CRLongCheck
        run: |
          mkdir -p out/CRLongCheck
          javac CRLongCheck/CRLongCheck.java -d out/CRLongCheck
          jar cfe CRLongCheck.jar CRLongCheck -C out/CRLongCheck .

      - name: Compile and package CRMeep
        run: |
          mkdir -p out/CRMeep
          javac CRMeep/CRMeep.java -d out/CRMeep
          jar cfe CRMeep.jar CRMeep -C out/CRMeep .

      - name: Compile and package CRNumberDisplayer
        run: |
          mkdir -p out/CRNumberDisplayer
          javac CRNumberDisplayer/CRNumberDisplayer.java -d out/CRNumberDisplayer
          jar cfe CRNumberDisplayer.jar CRNumberDisplayer -C out/CRNumberDisplayer .

      - name: Compile and package CRReverseString
        run: |
          mkdir -p out/CRReverseString
          javac CRReverseString/CRReverseString.java -d out/CRReverseString
          jar cfe CRReverseString.jar CRReverseString -C out/CRReverseString .

      - name: Compile and package CRRNG
        run: |
          mkdir -p out/CRRNG
          javac CRRNG/CRRNG.java -d out/CRRNG
          jar cfe CRRNG.jar CRRNG -C out/CRRNG .

      - name: Compile and package CRScreaming
        run: |
          mkdir -p out/CRScreaming
          javac CRScreaming/CRScreaming.java -d out/CRScreaming
          jar cfe CRScreaming.jar CRScreaming -C out/CRScreaming .

      - name: Compile and package CRScreaming2
        run: |
          mkdir -p out/CRScreaming2
          javac CRScreaming/CRScreaming2.java -d out/CRScreaming2
          jar cfe CRScreaming2.jar CRScreaming2 -C out/CRScreaming2 .

      - name: Compile and package CRSignedInttoUnsignedIntConverter
        run: |
          mkdir -p out/CRSignedInttoUnsignedIntConverter
          javac CRSignedInttoUnsignedIntConverter/CRSignedInttoUnsignedIntConverter.java -d out/CRSignedInttoUnsignedIntConverter
          jar cfe CRSignedInttoUnsignedIntConverter.jar CRSignedInttoUnsignedIntConverter -C out/CRSignedInttoUnsignedIntConverter .

      - name: Compile and package CRStringLengthIdentifier
        run: |
          mkdir -p out/CRStringLengthIdentifier
          javac CRStringLengthIdentifier/CRStringLengthIdentifier.java -d out/CRStringLengthIdentifier
          jar cfe CRStringLengthIdentifier.jar CRStringLengthIdentifier -C out/CRStringLengthIdentifier .

      - name: Compile and package CRStringReverser1
        run: |
          mkdir -p out/CRStringReverser1
          javac CRStringReversers/CRStringReverser.java -d out/CRStringReverser1
          jar cfe CRStringReverser1.jar CRStringReverser1 -C out/CRStringReverser1 .

      - name: Compile and package CRStringReverser2
        run: |
          mkdir -p out/CRStringReverser2
          javac CRStringReversers/CRStringReverser2.java -d out/CRStringReverser2
          jar cfe CRStringReverser2.jar CRStringReverser2 -C out/CRStringReverser2 .

      - name: Compile and package CRStringReverser3
        run: |
          mkdir -p out/CRStringReverser3
          javac CRStringReversers/CRStringReverser3.java -d out/CRStringReverser3
          jar cfe CRStringReverser3.jar CRStringReverser3 -C out/CRStringReverser3 .

      - name: Compile and package CRStringReverser4
        run: |
          mkdir -p out/CRStringReverser4
          javac CRStringReversers/CRStringReverser4.java -d out/CRStringReverser4
          jar cfe CRStringReverser4.jar CRStringReverser4 -C out/CRStringReverser4 .

      - name: Set output JAR list
        id: set-jars
        run: |
          echo "jars=CRAlgorithmCheck.jar CRCountTo1Million.jar CRForceCRC32.jar CRIntCheck.jar CRLongCheck.jar CRMeep.jar CRNumberDisplayer.jar CRReverseString.jar CRRNG.jar CRScreaming.jar CRScreaming2.jar CRSignedInttoUnsignedIntConverter.jar CRStringLengthIdentifier.jar CRStringReverser1.jar CRStringReverser2.jar CRStringReverser3.jar CRStringReverser4.jar" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: |
            CRAlgorithmCheck.jar
            CRCountTo1Million.jar
            CRForceCRC32.jar
            CRIntCheck.jar
            CRLongCheck.jar
            CRMeep.jar
            CRNumberDisplayer.jar
            CRReverseString.jar
            CRRNG.jar
            CRScreaming.jar
            CRScreaming2.jar
            CRSignedInttoUnsignedIntConverter.jar
            CRStringLengthIdentifier.jar
            CRStringReverser1.jar
            CRStringReverser2.jar
            CRStringReverser3.jar
            CRStringReverser4.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: jar-files
          path: ./jars

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          prerelease: ${{ github.event.inputs.release_type != 'main' }}
          files: |
            jars/CRAlgorithmCheck.jar
            jars/CRCountTo1Million.jar
            jars/CRForceCRC32.jar
            jars/CRIntCheck.jar
            jars/CRLongCheck.jar
            jars/CRMeep.jar
            jars/CRNumberDisplayer.jar
            jars/CRReverseString.jar
            jars/CRRNG.jar
            jars/CRScreaming.jar
            jars/CRScreaming2.jar
            jars/CRSignedInttoUnsignedIntConverter.jar
            jars/CRStringLengthIdentifier.jar
            jars/CRStringReverser1.jar
            jars/CRStringReverser2.jar
            jars/CRStringReverser3.jar
            jars/CRStringReverser4.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
